name: 'Send Slack Notification'
description: 'Sends deployment status notifications to Slack'

inputs:
  slack-webhook-url:
    description: 'Slack webhook URL'
    required: true
  status:
    description: 'Deployment status (success, failure, in-progress, completed-with-warnings)'
    required: true
  environment:
    description: 'Environment name (staging, production)'
    required: true
  commit-sha:
    description: 'Short commit SHA'
    required: false
  commit-message:
    description: 'Commit message'
    required: false
  commit-author:
    description: 'Commit author'
    required: false
  release-tag:
    description: 'Release tag (for production deployments)'
    required: false
  release-name:
    description: 'Release name (for production deployments)'
    required: false
  release-url:
    description: 'Release URL (for production deployments)'
    required: false
  heroku-app-name:
    description: 'Heroku app name'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Send Slack notification
      shell: bash
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
        STATUS: ${{ inputs.status }}
        ENVIRONMENT: ${{ inputs.environment }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        COMMIT_AUTHOR: ${{ inputs.commit-author }}
        RELEASE_TAG: ${{ inputs.release-tag }}
        RELEASE_NAME: ${{ inputs.release-name }}
        RELEASE_URL: ${{ inputs.release-url }}
        HEROKU_APP_NAME: ${{ inputs.heroku-app-name }}
      run: |
        # Determine emoji and title based on status
        case "$STATUS" in
          "success")
            EMOJI="✅"
            TITLE="Frontend ${ENVIRONMENT^} Deployment Successful"
            ;;
          "failure")
            EMOJI="❌"
            TITLE="Frontend ${ENVIRONMENT^} Deployment Failed"
            ;;
          "in-progress")
            EMOJI="🚀"
            TITLE="Frontend ${ENVIRONMENT^} Deployment In Progress"
            ;;
          "completed-with-warnings")
            EMOJI="⚠️"
            TITLE="Frontend ${ENVIRONMENT^} Deployment Completed with Warnings"
            ;;
        esac

        # Build base payload
        if [ "$STATUS" = "failure" ]; then
          # Failure notification
          if [ -n "$RELEASE_TAG" ]; then
            # Production failure
            payload=$(jq -n \
              --arg emoji "$EMOJI" \
              --arg title "$TITLE" \
              --arg env "$ENVIRONMENT" \
              --arg tag "$RELEASE_TAG" \
              --arg release_url "$RELEASE_URL" \
              --arg repo "${{ github.repository }}" \
              --arg run_id "${{ github.run_id }}" \
              '{
                text: "\($emoji) \($title)",
                blocks: [
                  {type: "header", text: {type: "plain_text", text: "\($emoji) \($title)"}},
                  {type: "section", fields: [
                    {type: "mrkdwn", text: "*Environment:*\n\($env | ascii_upcase)"},
                    {type: "mrkdwn", text: "*Release:*\n<\($release_url)|\($tag)>"},
                    {type: "mrkdwn", text: "*Workflow:*\n<https://github.com/\($repo)/actions/runs/\($run_id)|View Logs>"}
                  ]},
                  {type: "section", text: {type: "mrkdwn", text: "The deployment to Heroku Production failed. Please check the workflow logs for details."}}
                ]
              }')
          else
            # Staging failure
            payload=$(jq -n \
              --arg emoji "$EMOJI" \
              --arg title "$TITLE" \
              --arg env "$ENVIRONMENT" \
              --arg sha "$COMMIT_SHA" \
              --arg full_sha "${{ github.sha }}" \
              --arg author "$COMMIT_AUTHOR" \
              --arg message "$COMMIT_MESSAGE" \
              --arg repo "${{ github.repository }}" \
              --arg run_id "${{ github.run_id }}" \
              '{
                text: "\($emoji) \($title)",
                blocks: [
                  {type: "header", text: {type: "plain_text", text: "\($emoji) \($title)"}},
                  {type: "section", fields: [
                    {type: "mrkdwn", text: "*Environment:*\n\($env | ascii_upcase)"},
                    {type: "mrkdwn", text: "*Commit:*\n<https://github.com/\($repo)/commit/\($full_sha)|\($sha)>"},
                    {type: "mrkdwn", text: "*Author:*\n\($author)"},
                    {type: "mrkdwn", text: "*Workflow:*\n<https://github.com/\($repo)/actions/runs/\($run_id)|View Logs>"}
                  ]},
                  {type: "section", text: {type: "mrkdwn", text: "*Commit Message:*\n\($message)"}},
                  {type: "section", text: {type: "mrkdwn", text: "The deployment to Heroku failed. Please check the workflow logs for details."}}
                ]
              }')
          fi
        elif [ "$STATUS" = "in-progress" ]; then
          # In-progress notification (production only)
          payload=$(jq -n \
            --arg emoji "$EMOJI" \
            --arg title "$TITLE" \
            --arg env "$ENVIRONMENT" \
            --arg tag "$RELEASE_TAG" \
            --arg name "$RELEASE_NAME" \
            --arg app "$HEROKU_APP_NAME" \
            --arg release_url "$RELEASE_URL" \
            '{
              text: "\($emoji) \($title)",
              blocks: [
                {type: "header", text: {type: "plain_text", text: "\($emoji) \($title)"}},
                {type: "section", fields: [
                  {type: "mrkdwn", text: "*Environment:*\n\($env | ascii_upcase)"},
                  {type: "mrkdwn", text: "*Release:*\n<\($release_url)|\($tag)>"},
                  {type: "mrkdwn", text: "*Name:*\n\($name)"},
                  {type: "mrkdwn", text: "*App:*\n<https://\($app).herokuapp.com|View App>"}
                ]},
                {type: "section", text: {type: "mrkdwn", text: "_Deploying to Heroku..._"}}
              ]
            }')
        else
          # Success or completed-with-warnings
          if [ -n "$RELEASE_TAG" ]; then
            # Production success
            payload=$(jq -n \
              --arg emoji "$EMOJI" \
              --arg title "$TITLE" \
              --arg env "$ENVIRONMENT" \
              --arg tag "$RELEASE_TAG" \
              --arg name "$RELEASE_NAME" \
              --arg app "$HEROKU_APP_NAME" \
              --arg release_url "$RELEASE_URL" \
              --arg repo "${{ github.repository }}" \
              --arg run_id "${{ github.run_id }}" \
              '{
                text: "\($emoji) \($title)",
                blocks: [
                  {type: "header", text: {type: "plain_text", text: "\($emoji) \($title)"}},
                  {type: "section", fields: [
                    {type: "mrkdwn", text: "*Environment:*\n\($env | ascii_upcase)"},
                    {type: "mrkdwn", text: "*Release:*\n<\($release_url)|\($tag)>"},
                    {type: "mrkdwn", text: "*Name:*\n\($name)"},
                    {type: "mrkdwn", text: "*App:*\n<https://\($app).herokuapp.com|View App>"}
                  ]},
                  {type: "section", fields: [
                    {type: "mrkdwn", text: "*Workflow:*\n<https://github.com/\($repo)/actions/runs/\($run_id)|View Logs>"}
                  ]}
                ]
              }')
          else
            # Staging success
            payload=$(jq -n \
              --arg emoji "$EMOJI" \
              --arg title "$TITLE" \
              --arg env "$ENVIRONMENT" \
              --arg sha "$COMMIT_SHA" \
              --arg full_sha "${{ github.sha }}" \
              --arg author "$COMMIT_AUTHOR" \
              --arg message "$COMMIT_MESSAGE" \
              --arg repo "${{ github.repository }}" \
              --arg run_id "${{ github.run_id }}" \
              '{
                text: "\($emoji) \($title)",
                blocks: [
                  {type: "header", text: {type: "plain_text", text: "\($emoji) \($title)"}},
                  {type: "section", fields: [
                    {type: "mrkdwn", text: "*Environment:*\n\($env | ascii_upcase)"},
                    {type: "mrkdwn", text: "*Commit:*\n<https://github.com/\($repo)/commit/\($full_sha)|\($sha)>"},
                    {type: "mrkdwn", text: "*Author:*\n\($author)"},
                    {type: "mrkdwn", text: "*Workflow:*\n<https://github.com/\($repo)/actions/runs/\($run_id)|View Logs>"}
                  ]},
                  {type: "section", text: {type: "mrkdwn", text: "*Commit Message:*\n\($message)"}}
                ]
              }')
          fi
        fi

        curl -X POST "$SLACK_WEBHOOK_URL" \
          -H 'Content-Type: application/json' \
          -d "$payload"
